stages:
  - test

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - cd app # 我的应用放在了 app 目录下，所以需要先 cd 进去
    - cp leetcode-sample/settings.py.example leetcode-sample/settings.py # 我的 settings.py 被 gitignore 了，防止暴露一些敏感信息
    - pip3 install -r requirements.txt
    - python3 manage.py test
