# Generated by Django 2.2.4 on 2019-08-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sceneinfo',
            name='desc',
            field=models.TextField(default='', null=True, verbose_name='场景描述'),
        ),
        migrations.AlterField(
            model_name='sceneinfo',
            name='img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
