# Generated by Django 2.2 on 2019-08-02 06:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField()),
                ('mac_addr', models.CharField(max_length=20)),
                ('node_status', models.CharField(blank=True, choices=[('OFFLINE', 'offline'), ('IDLE', 'idle'), ('BUSY', 'busy')], default='IDLE', max_length=20)),
                ('loca_x', models.IntegerField(default=0)),
                ('loca_y', models.IntegerField(default=0)),
                ('version', models.CharField(default='0.0.1', max_length=10)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('psid', models.IntegerField(default=0)),
                ('is_delete', models.BooleanField(blank=True, default=False, verbose_name='逻辑删除')),
            ],
        ),
        migrations.CreateModel(
            name='NodeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_status', models.CharField(choices=[('T', 'transmitting'), ('R', 'receiving')], max_length=20)),
                ('radio', models.IntegerField()),
                ('power', models.IntegerField()),
                ('rate', models.CharField(max_length=20)),
                ('channel', models.IntegerField()),
                ('des_mac_addr', models.CharField(max_length=20)),
                ('psid', models.IntegerField()),
                ('payload', models.CharField(max_length=20)),
                ('pl_length', models.IntegerField()),
                ('periodic', models.BooleanField()),
                ('times', models.IntegerField()),
                ('tx_timeslot', models.IntegerField()),
                ('node', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='node_config', to='node.NodeInfo')),
                ('task', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='node_config', to='task.Task')),
            ],
        ),
    ]
